name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Install
        run: mvn clean install

      - name: Create directory
        run: mkdir app

      - name: Create project
        working-directory: app
        run: |
          mvn archetype:generate -B \
              -DarchetypeGroupId=com.thegreatapi \
              -DarchetypeArtifactId=quarkus-multimodule-archetype \
              -DarchetypeVersion=1.0.0-SNAPSHOT \
              -DgroupId=com.acme \
              -DartifactId=test \
              -Dversion=1.0.0-SNAPSHOT

      - name: Build with Maven
        working-directory: app/test
        run: mvn -B verify --file pom.xml
